clients:
  sbom:
      service_url: https://sbom-request.canonical.com
      department: charm_engineering
      email: tony.meyer@canonical.com
      team: charm_tech
  secscan: {}


artifacts:
  - name: 'concierge'
    type: 'snap'
    ssdlc_params:
        name: 'concierge'
        version: ''
        channel: 'stable'
        cycle: '25.10'
